import random

# This contains crops that grow depth range 0-60cm

# Kullanılacak özellikler
# Soil Texture (Sand, Silt, Clay %): Toprak dokusu (Kum, Silt, Kil %)
# pH: Toprak pH değeri
# Oranic Matter (%): Organik madde oranı
# Nitrogen (N) (%): Azot oranı
# Phosphorus (P) (ppm): Fosfor oranı
# Potassium (K) (ppm): Potasyum oranı
# Mositure Content (%): Toprak nem oranı
# Electrical Conductivity (dS/m): Elektriksel iletkenlik
# Soil Temperature (°C): Toprak sıcaklığı

# Ölçümü zor olan özellikler
# Cation Exchange Capacity (meq/100g): Kation değişim kapasitesi
# Calcium (Ca) (meq/100g): Kalsiyum oranı
# Magnesium (Mg) (meq/100g): Magnezyum oranı
# Sulphur (S) (ppm): Kükürt oranı
# Micronutrients(Ze,Fn,Mn,Cu,B) (ppm): Mikro besin elementleri oranı

# Kesin ölçüm için 12 değer gereklidir
# Şimdilik Shallow-Rooted Crops That Can Be Grown in Turkey (0–60 cm Root Depth) olan ürünler ile ilerlenecek



# "potato": {
#             "pH": round(random.uniform(5.0, 6.5), 2),
#             "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
#             "Organic Matter (%)": round(random.uniform(2.0, 5.0), 2),
#             "Nitrogen (N) (kg/ha)": round(random.uniform(50, 150), 2),
#             "Phosphorus (P) (kg/ha)": round(random.uniform(20, 50), 2),
#             "Potassium (K) (kg/ha)": round(random.uniform(100, 250), 2),
#             "Moisture Content (%)": round(random.uniform(60, 80), 2),
#             "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.2, 1.5), 2),
#             "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
#             "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
#             "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 150), 2),
#             "Sulfur (S) (mg/kg)": round(random.uniform(15, 50), 2),
#             "Zinc (Zn) (mg/kg)": round(random.uniform(0.5, 2.0), 2),
#             "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 10.0), 2),
#             "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 5.0), 2),
#             "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 1.0), 2),
#             "Boron (B) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
#             "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
#         },

crops = {
    "vegetables":{
        "lettuce": {
            "pH": round(random.uniform(6.0, 7.0), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam", "Silt Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(70, 85), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(500, 1000), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(60, 120), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.5), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.2), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Spinach": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam", "Clay Loam"]),
            "Organic Matter (%)": round(random.uniform(4.0, 7.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(100, 150), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 70), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(120, 250), 2),
            "Moisture Content (%)": round(random.uniform(60, 75), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.6, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(20, 30), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(600, 1200), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(70, 140), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(25, 50), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.5, 4.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(4.0, 10.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(3.0, 7.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.3, 1.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.4, 1.5), 2),
            "Soil Temperature (°C)": round(random.uniform(12, 22), 2)
        },
        "Onion": {
            "pH": round(random.uniform(6.0, 7.0), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam", "Clay Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 5.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Garlic": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(90, 130), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 70), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 75), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 120), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Cabbage": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam", "Clay Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(100, 150), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 80), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(150, 250), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(500, 1000), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(60, 120), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Radish": {
            "pH": round(random.uniform(6.0, 7.0), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam", "Silt Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 5.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 75), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Carrot": {
            "pH": round(random.uniform(6.0, 6.8), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam", "Silt Loam"]),
            "Organic Matter (%)": round(random.uniform(2.5, 5.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(70, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 75), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Bell Pepper": {
            "pH": round(random.uniform(6.0, 6.8), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 70), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        },
        "Eggplant": {
            "pH": round(random.uniform(5.5, 7.0), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 150), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 70), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        },
        "Tomato": {
            "pH": round(random.uniform(6.0, 6.8), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 70), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        },
        "Cucumber": {
            "pH": round(random.uniform(6.0, 7.0), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 70), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        },
        "Zucchini": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 70), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        }
    },
    "grains & cereals": {
        "Wheat": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Clay Loam"]),
            "Organic Matter (%)": round(random.uniform(2.0, 4.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(100, 150), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(80, 150), 2),
            "Moisture Content (%)": round(random.uniform(50, 70), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.4, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Barley": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Clay Loam"]),
            "Organic Matter (%)": round(random.uniform(2.0, 4.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(80, 150), 2),
            "Moisture Content (%)": round(random.uniform(50, 70), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.4, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Oats": {
            "pH": round(random.uniform(5.5, 7.0), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(2.0, 4.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(60, 100), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(20, 50), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(80, 150), 2),
            "Moisture Content (%)": round(random.uniform(50, 70), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.4, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Corn": {
            "pH": round(random.uniform(5.8, 7.0), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(2.0, 5.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(100, 200), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        }
    },
    "legumes": {
        "Lentil": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(2.0, 4.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(20, 40), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(20, 50), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(50, 100), 2),
            "Moisture Content (%)": round(random.uniform(50, 70), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.4, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Chickpea": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(2.0, 4.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(20, 40), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(20, 50), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(50, 100), 2),
            "Moisture Content (%)": round(random.uniform(50, 70), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.4, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Bean": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(2.0, 4.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(20, 40), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(20, 50), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(50, 100), 2),
            "Moisture Content (%)": round(random.uniform(50, 70), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.4, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        },
        "Peas": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(2.0, 4.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(20, 40), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(20, 50), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(50, 100), 2),
            "Moisture Content (%)": round(random.uniform(50, 70), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.4, 1.2), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(10, 20), 2)
        }
    },
    "fruits": {
        "Strawberry": {
            "pH": round(random.uniform(5.5, 6.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(50, 100), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        },
        "Melon": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 70), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        },
        "Watermelon": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(80, 120), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(40, 70), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(15, 25), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(400, 800), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(50, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(20, 40), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 3.0), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(3.0, 8.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(2.0, 5.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.2, 1.0), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.3, 1.0), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        }
    },
    "herbs": {
        "Basil": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(50, 100), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        },
        "Parsley": {
            "pH": round(random.uniform(6.0, 7.0), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(50, 100), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        },
        "Mint": {
            "pH": round(random.uniform(6.0, 7.5), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(3.0, 6.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(50, 100), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(30, 60), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(100, 200), 2),
            "Moisture Content (%)": round(random.uniform(60, 80), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        },
        "Thyme": {
            "pH": round(random.uniform(6.0, 8.0), 2),
            "Soil Texture": random.choice(["Loamy", "Sandy Loam"]),
            "Organic Matter (%)": round(random.uniform(2.0, 4.0), 2),
            "Nitrogen (N) (kg/ha)": round(random.uniform(30, 60), 2),
            "Phosphorus (P) (kg/ha)": round(random.uniform(20, 50), 2),
            "Potassium (K) (kg/ha)": round(random.uniform(50, 100), 2),
            "Moisture Content (%)": round(random.uniform(50, 70), 2),
            "Electrical Conductivity (EC) (dS/m)": round(random.uniform(0.5, 1.5), 2),
            "Cation Exchange Capacity (CEC) (meq/100g)": round(random.uniform(10, 20), 2),
            "Calcium (Ca) (mg/kg)": round(random.uniform(300, 700), 2),
            "Magnesium (Mg) (mg/kg)": round(random.uniform(40, 100), 2),
            "Sulfur (S) (mg/kg)": round(random.uniform(15, 30), 2),
            "Zinc (Zn) (mg/kg)": round(random.uniform(1.0, 2.5), 2),
            "Iron (Fe) (mg/kg)": round(random.uniform(2.0, 6.0), 2),
            "Manganese (Mn) (mg/kg)": round(random.uniform(1.0, 4.0), 2),
            "Copper (Cu) (mg/kg)": round(random.uniform(0.1, 0.8), 2),
            "Boron (B) (mg/kg)": round(random.uniform(0.2, 0.8), 2),
            "Soil Temperature (°C)": round(random.uniform(15, 25), 2)
        }
    }
}